### ISSUE TITLE
Needs permission to sign in API Center portal

### ISSUE THREAD

**Issue by v-jiaodi** [Azure-Samples/APICenter-Reference#28]
**Describe the issue:**

According to `README` test, when executing step 7: Click the button `Sign in`, the following issues were encountered:

![image](https://github.com/Azure-Samples/APICenter-Reference/assets/80496810/5ca5b4df-eb2e-4322-85dc-cfaa84757791)

**Repro Steps:**

1. Login in with command: `azd auth login` and `az login`.
2. Execute command: `azd up`.
3. Find the Azure Static Web App instance name ending with `-portal` and open the app to see the API Center portal.

**Environment:**
- OS: Windows, Codespace
- Azd version : 1.9.3

**Expected behavior:**
Click `Sign in` can pass.

@justinyoo and @hemarina   for notification.

**Comment by justinyoo** [comment]
@v-jiaodi If it's run within the microsoft.com tenant, you'll see this error, which is expected. Would you please be able to try outside microsoft.com tenant? If it's done outside microsft.com tenant, your account should have enough permission for the app to be granted.
