### ISSUE TITLE
Error executing `azd up` command due to missing .NET 8 SDK

### ISSUE THREAD

**Issue by glaucia86** [Azure-Samples/APICenter-Reference#32]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

I followed the guidance in the README.md file at:

# Authenticate with Azure Developer CLI
azd auth login

# Authenticate with Azure CLI
az login

And finally run the command: `azd up`. After it tries to provision, I get the following error:

![image](https://github.com/Azure-Samples/APICenter-Reference/assets/1631477/1b735e6b-f6af-44df-aa4d-42d6805dca07)

What should we improve?

If the example contains code in .NET and Node.js in the same repository (although I disagree), I recommend that you indicate in the documentation or in the README.md that it includes the .NET version 8 downloads.

p.s.: include the .NET version to download **[HERE](https://dotnet.microsoft.com/pt-br/download/dotnet/8.0)** in the README.md file. Once some JavaScript Developers can try it out this sample and they will try to test and will ask for this .NET version

I think that for a better experience it would be better to split this repository for `dotnet` and another for `nodejs`.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Windows 11

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

![image](https://github.com/Azure-Samples/APICenter-Reference/assets/1631477/0bda88e7-137a-4d75-9fb7-559b03e3c543)

**Comment by justinyoo** [comment]
@glaucia86 Oh, that's right. It should have included the prerequisites section. I'll check that out.
