### ISSUE TITLE
[feat] Add support for multiple container images in `devcontainer.json` file

### ISSUE THREAD

**Issue by glaucia86** [Azure-Samples/APICenter-Reference#34]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

---

In the `devcontainer.json` file, you are only using the dotnet image in the `image` property. Since the project includes both dotnet and nodejs solutions, we need to adopt multiple containers.

**Line**: [devcontainer.json](https://github.com/Azure-Samples/APICenter-Reference/blob/main/.devcontainer/devcontainer.json#L4)
---

Or maybe use a `dockerfile`. I would like to hear from you first

* Some solutions
  * [Configure separate containers](https://code.visualstudio.com/remote/advancedcontainers/configure-separate-containers)
  * [Working with Multiple Dev Containers in VS Code](https://www.youtube.com/watch?v=bVmczgfeR5Y)

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by justinyoo** [comment]
Not really. It has both .NET 6/7/8 and the latest version of node LTS

https://github.com/Azure-Samples/APICenter-Reference/blob/52c73439c9cf1b5a53472481dd31281663f87036/.devcontainer/devcontainer.json#L20
