### ISSUE TITLE
[feat] resolve version conflict in `devcontainer.json` for `dotnet` image

### ISSUE THREAD

**Issue by glaucia86** [Azure-Samples/APICenter-Reference#35]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

In the devcontainer.json file, the image used is version 8 of dotnet. However, the version indicated in the configuration is 6.0 (as you can see **[here](https://github.com/Azure-Samples/APICenter-Reference/blob/main/.devcontainer/devcontainer.json#L16)**, which may cause a conflict. The correct configuration should be:

```json
"ghcr.io/devcontainers/features/docker-in-docker:latest": {},
"ghcr.io/devcontainers/features/dotnet:latest": {
  "version": "8.0",
  "additionalVersions": "6.0,7.0"
},
```

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by justinyoo** [comment]
Not really. It's for some extension's backward compatibility. There's no version conflict.
